ProyectoFinal/ProyectoFinal/Models/Ingresos.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProyectoFinal.Models
{
    public class Ingresos
    {
        [Key]
        public int IdIngresos { set; get; }

        [Required]
        public int Paciente_Id { set; get; }
        [ForeignKey("Paciente_Id")]
        public Pacientes Pacientes { set; get; }

        [Required]
        public int Habitacion_Id { set; get; }
        [ForeignKey("Habitacion_Id")]
        public Habitaciones Habitaciones { set; get; }
        [Required]
        public string Fecha_Ingreso { set; get; }
    }
}

ProyectoFinal/ProyectoFinal/Controllers/IngresosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Models;
//using Rotativa;

namespace ProyectoFinal.Controllers
{
    public class IngresosController : Controller
    {
        private HospitalContext db = new HospitalContext();

        // GET: Ingresos
        public ActionResult Index()
        {
            var ingresos = db.Ingresos.Include(i => i.Habitaciones).Include(i => i.Pacientes);
            return View(ingresos.ToList());
        }

        [HttpPost]
        public ActionResult Index(string select, string buscar)
        {
            if (select == "Fecha")
            {
                var ingresos = db.Ingresos.Include(c => c.Habitaciones).Include(c => c.Pacientes).Where(a => a.Fecha_Ingreso.Contains(buscar));
                return View(ingresos.ToList());

            }
            else if (select == "Habitacion")               
            {

                int datos = (from a in db.Habitaciones
                            where a.Numero == buscar
                            select a.IdHabitacion).SingleOrDefault();

                var ingresos = db.Ingresos.Include(i => i.Habitaciones).Include(i => i.Pacientes).Where(e => e.Habitacion_Id.Equals(datos));
                return View(ingresos.ToList());
            }

            return View();

        }

        /*public ActionResult Imprimir()
        {
            var print = new ActionAsPdf("Index");
            return print;
        }*/

        // GET: Ingresos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingresos ingresos = db.Ingresos.Find(id);
            if (ingresos == null)
            {
                return HttpNotFound();
            }
            return View(ingresos);
        }

        // GET: Ingresos/Create
        public ActionResult Create()
        {
            ViewBag.Habitacion_Id = new SelectList(db.Habitaciones, "IdHabitacion", "IdHabitacion");
            ViewBag.Paciente_Id = new SelectList(db.Pacientes, "IdPacientes", "IdPacientes");
            return View();
        }

        // POST: Ingresos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdIngresos,Paciente_Id,Habitacion_Id,Fecha_Ingreso")] Ingresos ingresos)
        {
            if (ModelState.IsValid)
            {
                db.Ingresos.Add(ingresos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Habitacion_Id = new SelectList(db.Habitaciones, "IdHabitacion", "Tipo", ingresos.Habitacion_Id);
            ViewBag.Paciente_Id = new SelectList(db.Pacientes, "IdPacientes", "Cedula", ingresos.Paciente_Id);
            return View(ingresos);
        }

        // GET: Ingresos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingresos ingresos = db.Ingresos.Find(id);
            if (ingresos == null)
            {
                return HttpNotFound();
            }
            ViewBag.Habitacion_Id = new SelectList(db.Habitaciones, "IdHabitacion", "Tipo", ingresos.Habitacion_Id);
            ViewBag.Paciente_Id = new SelectList(db.Pacientes, "IdPacientes", "Cedula", ingresos.Paciente_Id);
            return View(ingresos);
        }

        // POST: Ingresos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdIngresos,Paciente_Id,Habitacion_Id,Fecha_Ingreso")] Ingresos ingresos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ingresos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Habitacion_Id = new SelectList(db.Habitaciones, "IdHabitacion", "Tipo", ingresos.Habitacion_Id);
            ViewBag.Paciente_Id = new SelectList(db.Pacientes, "IdPacientes", "Cedula", ingresos.Paciente_Id);
            return View(ingresos);
        }

        // GET: Ingresos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ingresos ingresos = db.Ingresos.Find(id);
            if (ingresos == null)
            {
                return HttpNotFound();
            }
            return View(ingresos);
        }

        // POST: Ingresos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Ingresos ingresos = db.Ingresos.Find(id);
            db.Ingresos.Remove(ingresos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/ProyectoFinal/Views/Ingresos/Create.cshtml
@model ProyectoFinal.Models.Ingresos

@{
    ViewBag.Title = "Create Ingresos";
}

<h2>Create Ingresos</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Paciente_Id, "ID Paciente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Paciente_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Paciente_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Habitacion_Id, "ID Habitación", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Habitacion_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Habitacion_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Ingreso,"Fecha de ingreso", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Ingreso, new { htmlAttributes = new { @class = "form-control", type="date"  } })
                @Html.ValidationMessageFor(model => model.Fecha_Ingreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProyectoFinal/ProyectoFinal/Views/Ingresos/Delete.cshtml
@model ProyectoFinal.Models.Ingresos

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ingresos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Habitaciones.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Habitaciones.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pacientes.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pacientes.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Ingreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Ingreso)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProyectoFinal/ProyectoFinal/Views/Ingresos/Details.cshtml
@model ProyectoFinal.Models.Ingresos

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Ingresos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Habitaciones.Tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Habitaciones.Tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pacientes.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pacientes.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha_Ingreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha_Ingreso)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdIngresos }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProyectoFinal/ProyectoFinal/Views/Ingresos/Edit.cshtml
@model ProyectoFinal.Models.Ingresos

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ingresos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdIngresos)

        <div class="form-group">
            @Html.LabelFor(model => model.Paciente_Id, "Paciente_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Paciente_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Paciente_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Habitacion_Id, "Habitacion_Id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Habitacion_Id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Habitacion_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha_Ingreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha_Ingreso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fecha_Ingreso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProyectoFinal/ProyectoFinal/Views/Ingresos/Index.cshtml
@model IEnumerable<ProyectoFinal.Models.Ingresos>

@{
    ViewBag.Title = "Tabla Ingresos";
}

<h2>Tabla Ingresos</h2>
<div>
    @using (Html.BeginForm("Index", "Ingresos", FormMethod.Post))
    {
        <h5>Consultar</h5>
        <div class="row">
            <select name="select" class="form-control col col-lg-2" required="required">
                <option value="">Opciones</option>
                <option value="Fecha">Fecha</option>
                <option value="Habitacion">Habitacion</option>
            </select>

            @Html.TextBox("buscar", "", new { @class = "form-control col-md-4", placeholder = "Consulta", required = "required" })

        <div class="col-2">
            <button type="submit" class="btn btn-danger">Consultar</button>
            <button onclick="reportepdf()" class="btn btn-danger">Imprimir</button>
        </div>
        </div>
    }
</div>
<p>
    @Html.ActionLink("--Create New ", "Create")
</p>
<table class="table" id="documento">
    <tr>
        <th>
            @Html.DisplayName("Número Habitación")
        </th>
        <th>
            @Html.DisplayName("Nombre Paciente")
        </th>
        <th>
            @Html.DisplayName("Fecha de ingreso")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Habitaciones.Numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pacientes.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha_Ingreso)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.IdIngresos }) |
                @Html.ActionLink("Details", "Details", new { id = item.IdIngresos }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IdIngresos })
            </td>
        </tr>
    }

</table>