ProyectoFinal/ProyectoFinal/Models/Pacientes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ProyectoFinal.Models
{
    public class Pacientes
    {
        [Key]
        public int IdPacientes { set; get; }
        [Required]
        public string Cedula { set; get; }
        [Required]
        public string Nombre { set; get; }
        [Required]
        public bool Asegurado { set; get; }
    }
}

ProyectoFinal/ProyectoFinal/Controllers/PacientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Models;
//using Rotativa;

namespace ProyectoFinal.Controllers
{
    public class PacientesController : Controller
    {
        private HospitalContext db = new HospitalContext();

        // GET: Pacientes
        public ActionResult Index()
        {
            return View(db.Pacientes.ToList());
        }

        [HttpPost]
        public ActionResult Index(string select, string buscar)
        {
            if (select == "Nombre")
            {
                var datos = from d in db.Pacientes
                           select d;

                datos = datos.Where(a => a.Nombre.Contains(buscar));

                return View(datos);

            }
            else if (select == "Asegurado")
            {
                if (buscar == "Si" || buscar == "si" || buscar == "SI" || buscar == "sI")
                {
                    var datos = from d in db.Pacientes
                               where d.Asegurado.Equals(true)
                               select d;

                    return View(datos);

                }
                else if (buscar == "No" || buscar == "no" || buscar == "NO" || buscar == "nO")
                {
                    var datos = from d in db.Pacientes
                               where d.Asegurado.Equals(false)
                               select d;

                    return View(datos);
                }
            }
            else if (select == "Cedula")
            {

                var datos = from d in db.Pacientes
                           select d;

                datos = datos.Where(a => a.Cedula.Contains(buscar));
                return View(datos);

            }
            return View();

        }

        /*public ActionResult Imprimir()
        {
            var print = new ActionAsPdf("Index");
            return print;
        }*/ 

        // GET: Pacientes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacientes pacientes = db.Pacientes.Find(id);
            if (pacientes == null)
            {
                return HttpNotFound();
            }
            return View(pacientes);
        }

        // GET: Pacientes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pacientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPacientes,Cedula,Nombre,Asegurado")] Pacientes pacientes)
        {
            if (ModelState.IsValid)
            {
                db.Pacientes.Add(pacientes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pacientes);
        }

        // GET: Pacientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacientes pacientes = db.Pacientes.Find(id);
            if (pacientes == null)
            {
                return HttpNotFound();
            }
            return View(pacientes);
        }

        // POST: Pacientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPacientes,Cedula,Nombre,Asegurado")] Pacientes pacientes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pacientes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pacientes);
        }

        // GET: Pacientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pacientes pacientes = db.Pacientes.Find(id);
            if (pacientes == null)
            {
                return HttpNotFound();
            }
            return View(pacientes);
        }

        // POST: Pacientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pacientes pacientes = db.Pacientes.Find(id);
            db.Pacientes.Remove(pacientes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/ProyectoFinal/Views/Pacientes/Create.cshtml
@model ProyectoFinal.Models.Pacientes

@{
    ViewBag.Title = "Create Pacientes";
}

<h2>Create Pacientes</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Cedula,"Cédula", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Asegurado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Asegurado)
                    @Html.ValidationMessageFor(model => model.Asegurado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProyectoFinal/ProyectoFinal/Views/Pacientes/Delete.cshtml
@model ProyectoFinal.Models.Pacientes

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pacientes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Asegurado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Asegurado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProyectoFinal/ProyectoFinal/Views/Pacientes/Details.cshtml
@model ProyectoFinal.Models.Pacientes

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pacientes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Asegurado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Asegurado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdPacientes }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProyectoFinal/ProyectoFinal/Views/Pacientes/Edit.cshtml
@model ProyectoFinal.Models.Pacientes

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pacientes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdPacientes)

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Asegurado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Asegurado)
                    @Html.ValidationMessageFor(model => model.Asegurado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProyectoFinal/ProyectoFinal/Views/Pacientes/Index.cshtml
@model IEnumerable<ProyectoFinal.Models.Pacientes>

@{
    ViewBag.Title = "Tabla Pacientes";
}

<h2>Tabla Pacientes</h2>
<div>
    @using (Html.BeginForm("Index", "Pacientes", FormMethod.Post))
    {
        <h5>Consultar</h5>
        <div class="row">
            <select name="select" class="form-control col col-lg-2" required="required">
                <option value="">Opciones</option>
                <option value="Nombre">Nombre</option>
                <option value="Cedula">Cedula</option>
                <option value="Asegurado">Asegurado</option>
            </select>

            @Html.TextBox("buscar", "", new { @class = "form-control col-md-4", placeholder = "Consulta", required = "required" })

        <div class="col-2">
            <button type="submit" class="btn btn-danger">Consultar</button>
            <button onclick="reportepdf()" class="btn btn-danger">Imprimir</button>
        </div>
        </div>
    }
</div>
<p>
    @Html.ActionLink("--Create New ", "Create")
</p>
<table class="table" id="documento">
    <tr>
        <th>
            @Html.DisplayName("Cédula")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Asegurado)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cedula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Asegurado)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.IdPacientes }) |
                @Html.ActionLink("Details", "Details", new { id = item.IdPacientes }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IdPacientes })
            </td>
        </tr>
    }

</table>