ProyectoFinal/ProyectoFinal/Controllers/AltasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Models;
//using Rotativa;

namespace ProyectoFinal.Controllers
{
    public class AltasController : Controller
    {
        private HospitalContext db = new HospitalContext();

        // GET: Altas
        public ActionResult Index()
        {
            var altas = db.Altas.Include(a => a.Ingresos);
            return View(altas.ToList());
        }

        [HttpPost]
        public ActionResult Index(string select, string buscar)
        {
            if (select == "Fecha")
            {
                var altas = db.Altas.Include(c => c.Ingresos).Where(a => a.Fecha_Salida==buscar);

                try { 
                ViewBag.total = altas.Sum(c => c.Total_Pagar);
                ViewBag.cont = altas.Count();
                ViewBag.min = altas.Min(c => c.Total_Pagar);
                ViewBag.max = altas.Max(c => c.Total_Pagar);
                ViewBag.prom = altas.Average(c => c.Total_Pagar);

                return View(altas.ToList());
                }
                catch(Exception e)
                {
                    return View(altas.ToList());
                }

            }
            
            else if (select == "Paciente")
            {
                
                var altas = db.Altas.Include(c => c.Ingresos).Where(a => a.Nombre == buscar);

                try { 
                ViewBag.total = altas.Sum(c => c.Total_Pagar);
                ViewBag.cont = altas.Count();
                ViewBag.min = altas.Min(c => c.Total_Pagar);
                ViewBag.max = altas.Max(c => c.Total_Pagar);
                ViewBag.prom = altas.Average(c => c.Total_Pagar);

                return View(altas.ToList());
                }
                catch(Exception e)
                {
                    return View(altas.ToList());
                }

            }
            return View();

        }

        /*public ActionResult Imprimir()
        {
            var print = new ActionAsPdf("Index");
            return print;
        }*/

        // GET: Altas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Altas altas = db.Altas.Find(id);
            if (altas == null)
            {
                return HttpNotFound();
            }
            return View(altas);
        }

        // GET: Altas/Create
        public ActionResult Create()
        {
            ViewBag.Ingreso_Id = new SelectList(db.Ingresos, "IdIngresos", "IdIngresos");
            return View();

        }

        // POST: Altas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdAltas,Ingreso_Id,Fecha_Ingreso,Nombre,Numero,Fecha_Salida,Monto,Total_Pagar")] Altas altas)
        {
            if (ModelState.IsValid)
            {
                db.Altas.Add(altas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Ingreso_Id = new SelectList(db.Ingresos, "IdIngresos", "Fecha_Ingreso", altas.Ingreso_Id);
            return View(altas);
        }

        // GET: Altas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Altas altas = db.Altas.Find(id);
            if (altas == null)
            {
                return HttpNotFound();
            }
            ViewBag.Ingreso_Id = new SelectList(db.Ingresos, "IdIngresos", "Fecha_Ingreso", altas.Ingreso_Id);
            return View(altas);
        }

        // POST: Altas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdAltas,Ingreso_Id,Fecha_Ingreso,Nombre,Numero,Fecha_Salida,Monto,Total_Pagar")] Altas altas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(altas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Ingreso_Id = new SelectList(db.Ingresos, "IdIngresos", "Fecha_Ingreso", altas.Ingreso_Id);
            return View(altas);
        }

        // GET: Altas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Altas altas = db.Altas.Find(id);
            if (altas == null)
            {
                return HttpNotFound();
            }
            return View(altas);
        }

        // POST: Altas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Altas altas = db.Altas.Find(id);
            db.Altas.Remove(altas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult Nombre(int idPaciente)
        {

            var datos = (from i in db.Ingresos
                             join p in db.Pacientes
                             on i.Paciente_Id equals p.IdPacientes
                             where i.IdIngresos == idPaciente
                             select p.Nombre).ToList();
            return Json(datos);
        }

        public JsonResult Monto(int idPaciente)
        {

            var datos = (from i in db.Ingresos
                             join h in db.Habitaciones
                             on i.Habitacion_Id equals h.IdHabitacion
                             where i.IdIngresos == idPaciente
                             select h.Precio).ToList();
            return Json(datos);
        }

        public JsonResult FechaIngreso(int idPaciente)
        {

            var datos = (from i in db.Ingresos
                             where i.IdIngresos == idPaciente
                             select i.Fecha_Ingreso).ToList();
            return Json(datos);
        }

        public JsonResult NumeroHabitacion(int idPaciente)
        {

            var datos = (from i in db.Ingresos
                             join h in db.Habitaciones
                             on i.Habitacion_Id equals h.IdHabitacion
                             where i.IdIngresos == idPaciente
                             select h.Numero).ToList();
            return Json(datos);
        }
            
    }
}

ProyectoFinal/ProyectoFinal/Controllers/CitasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Models;
//using Rotativa;

namespace ProyectoFinal.Controllers
{
    public class CitasController : Controller
    {
        private HospitalContext db = new HospitalContext();

        // GET: Citas
        public ActionResult Index()
        {
            var citas = db.Citas.Include(c => c.Medicos).Include(c => c.Pacientes);
            return View(citas.ToList());
        }

        [HttpPost]
        public ActionResult Index(string select, string buscar)
        {
            if (select == "Fecha")
            {
                var citas = db.Citas.Include(c => c.Medicos).Include(c => c.Pacientes).Where(a => a.Fecha.Contains(buscar));
                return View(citas.ToList());

            }
            else if (select == "Doctor")
            {

                var datos = (from d in db.Medicos
                            where d.Nombre == buscar
                            select d.IdMedicos).SingleOrDefault();

                var citas = db.Citas.Include(c => c.Medicos).Include(c => c.Pacientes).Where(a => a.Medico_Id.Equals(datos));
                return View(citas.ToList());
            }
            else if (select == "Paciente")
            {
                var datos = (from d in db.Pacientes
                            where d.Nombre == buscar
                            select d.IdPacientes).SingleOrDefault();

                var citas = db.Citas.Include(c => c.Medicos).Include(c => c.Pacientes).Where(a => a.Paciente_Id.Equals(datos));
                return View(citas.ToList());

            }

            return View();

        }

        /*public ActionResult Imprimir()
        {
            var print = new ActionAsPdf("Index");
            return print;
        }*/

        // GET: Citas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Citas citas = db.Citas.Find(id);
            if (citas == null)
            {
                return HttpNotFound();
            }
            return View(citas);
        }

        // GET: Citas/Create
        public ActionResult Create()
        {
            ViewBag.Medico_Id = new SelectList(db.Medicos, "IdMedicos", "IdMedicos");
            ViewBag.Paciente_Id = new SelectList(db.Pacientes, "IdPacientes", "IdPacientes");
            return View();
        }

        // POST: Citas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdCitas,Paciente_Id,Medico_Id,Fecha,Hora")] Citas citas)
        {
            if (ModelState.IsValid)
            {
                db.Citas.Add(citas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Medico_Id = new SelectList(db.Medicos, "IdMedicos", "Nombre", citas.Medico_Id);
            ViewBag.Paciente_Id = new SelectList(db.Pacientes, "IdPacientes", "Cedula", citas.Paciente_Id);
            return View(citas);
        }

        // GET: Citas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Citas citas = db.Citas.Find(id);
            if (citas == null)
            {
                return HttpNotFound();
            }
            ViewBag.Medico_Id = new SelectList(db.Medicos, "IdMedicos", "Nombre", citas.Medico_Id);
            ViewBag.Paciente_Id = new SelectList(db.Pacientes, "IdPacientes", "Cedula", citas.Paciente_Id);
            return View(citas);
        }

        // POST: Citas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdCitas,Paciente_Id,Medico_Id,Fecha,Hora")] Citas citas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(citas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Medico_Id = new SelectList(db.Medicos, "IdMedicos", "Nombre", citas.Medico_Id);
            ViewBag.Paciente_Id = new SelectList(db.Pacientes, "IdPacientes", "Cedula", citas.Paciente_Id);
            return View(citas);
        }

        // GET: Citas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Citas citas = db.Citas.Find(id);
            if (citas == null)
            {
                return HttpNotFound();
            }
            return View(citas);
        }

        // POST: Citas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Citas citas = db.Citas.Find(id);
            db.Citas.Remove(citas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/ProyectoFinal/Controllers/MedicosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoFinal.Models;
//using Rotativa;

namespace ProyectoFinal.Controllers
{
    public class MedicosController : Controller
    {
        private HospitalContext db = new HospitalContext();

        // GET: Medicos
        public ActionResult Index()
        {
            return View(db.Medicos.ToList());
        }
        [HttpPost]
        public ActionResult Index(string select, string buscar)
        {
            if (select == "Nombre")
            {
                var datos = from d in db.Medicos
                           select d;

                datos = datos.Where(a => a.Nombre.Contains(buscar));

                return View(datos);

            }
            else if (select == "Especialidad")
            {

                var datos = from d in db.Medicos
                           select d;

                datos = datos.Where(a => a.Especialidad.Contains(buscar));
                return View(datos);

            }
            return View();

        }

        /*public ActionResult Imprimir()
        {
            var print = new ActionAsPdf("Index");
            return print;
        }*/

        // GET: Medicos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = db.Medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        // GET: Medicos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Medicos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdMedicos,Nombre,Exequatur,Especialidad")] Medicos medicos)
        {
            if (ModelState.IsValid)
            {
                db.Medicos.Add(medicos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(medicos);
        }

        // GET: Medicos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = db.Medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        // POST: Medicos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdMedicos,Nombre,Exequatur,Especialidad")] Medicos medicos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(medicos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(medicos);
        }

        // GET: Medicos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Medicos medicos = db.Medicos.Find(id);
            if (medicos == null)
            {
                return HttpNotFound();
            }
            return View(medicos);
        }

        // POST: Medicos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Medicos medicos = db.Medicos.Find(id);
            db.Medicos.Remove(medicos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoFinal/ProyectoFinal/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProyectoFinal/ProyectoFinal/Views/Home/Consultas.cshtml
@{
    ViewBag.Title = "Consultas";
}
<br />
<h2>Consultas</h2>
<br />
<div class="container mt-5">
    <div>
        <div class="row">
            <div class="col-4">
                <div class="card border-info" style="width: 18rem;">
                    <img src="~/img/medicos.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                    <div class="card-body">
                        <h5 class="card-title"><b>Médicos</b></h5>
                        <p class="card-text" align="justify">En el siguiente módulo se pueden realizar consultas en la tabla médicos </p>

                        @Html.ActionLink("Llévame al módulo", "Index", "Medicos", "", new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
            <br />
            <div class="col-4">
                <div class="card border-info" style="width: 18rem;">
                    <img src="~/img/paciente.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                    <div class="card-body">
                        <h5 class="card-title"><b>Pacientes</b></h5>
                        <p class="card-text" align="justify">En el siguiente modulo se pueden realizar consultas en la tabla pacientes</p>
                        @Html.ActionLink("Llévame al módulo", "Index", "Pacientes", "", new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
            <br />
            <div class="col-4">
                <div class="card border-info" style="width: 18rem;">
                    <img src="~/img/habitacion.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                    <div class="card-body">
                        <h5 class="card-title"><b>Habitaciones</b></h5>
                        <p class="card-text" align="justify">En el siguiente modulo se pueden realizar consultas en la tabla habitaciones</p>
                        @Html.ActionLink("Llévame al módulo", "Index", "Habitaciones", "", new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
        </div>
        <br />
        <div>
            <div class="row">
                <div class="col-4">
                    <div class="card border-info" style="width: 18rem;">
                        <img src="~/img/citas.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                        <div class="card-body">
                            <h5 class="card-title"><b>Citas Médicas</b></h5>
                            <p class="card-text" align="justify">En el siguiente modulo se pueden realizar consultas en la tabla citas</p>
                            @Html.ActionLink("Llévame al módulo", "Index", "Citas", "", new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
                <br />
                <div class="col-4">
                    <div class="card border-info" style="width: 18rem;">
                        <img src="~/img/ingreso.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                        <div class="card-body">
                            <h5 class="card-title"><b>Ingresos</b></h5>
                            <p class="card-text" align="justify">En el siguiente modulo se pueden realizar consultas en la tabla ingresos</p>
                            @Html.ActionLink("Llévame al módulo", "Index", "Ingresos", "", new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
                <br />
                <div class="col-4">
                    <div class="card border-info" style="width: 18rem;">
                        <img src="~/img/alta.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                        <div class="card-body">
                            <h5 class="card-title"><b>Alta médica</b></h5>
                            <p class="card-text" align="justify">En el siguiente modulo se pueden realizar consultas en la tabla altas</p>
                            @Html.ActionLink("Llévame al módulo", "Index", "Altas", "", new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

ProyectoFinal/ProyectoFinal/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProyectoFinal/ProyectoFinal/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Sistema control médico";
}

<div class="jumbotron" style="background-image:url(../img/medico.jpg); height: 400px; width:1150px;">

</div>

    <h4 class="text-info"><font color="black"><b>Módulos</b></font></h4>
<div class="row">

    <div class="col-md-4">

        <div class="card border-info mb-3" style="max-width: 18rem;">
            <div class="card-header text-info font-weight-bold"><font color="black"><b>Módulo 1:</b></font></div>
            <div class="card-body text-info">
                <font color="black">
                    <h5 class="card-title"><b>Mantenimientos</b></h5>
                </font>
                <font color="black">
                    <p class="card-text" align="justify">Este módulo consiste en crear formularios que alimentan ciertas tablas</p>
                </font>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card border-info mb-3" style="max-width: 18rem;">
            <div class="card-header text-info font-weight-bold"><font color="black"><b>Módulo 2:</b></font></div>
            <div class="card-body text-info">
                <font color="black">
                    <h5 class="card-title"><b>Procesos</b></h5>
                    <p class="card-text" align="justify">En este módulo se van a configurar algunos procesos, estos procesos serán registrados</p>
                </font>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card border-info mb-3" style="max-width: 18rem;">
            <div class="card-header text-info font-weight-bold"><font color="black"><b>Módulo 3:</b></font></div>
            <div class="card-body text-info">
                <font color="black">
                    <h5 class="card-title"><b>Consultas</b></h5>
                    <p class="card-text" align="justify">En este módulo se pueden realizar consultas en la base de datos </p>
                </font>
            </div>
        </div>
    </div>
</div>

ProyectoFinal/ProyectoFinal/Views/Home/Mantenimientos.cshtml
@{
    ViewBag.Title = "Mantenimientos";
}
<br />
<h2>Mantenimientos</h2>
<br />
    <div class="container mt-5">
        <div class="row">
            <div class="col-4">
                <div class="card border-info" style="width: 18rem;">
                    <img src="~/img/medicos.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                    <div class="card-body">
                        <h5 class="card-title"><b>Médicos</b></h5>
                        <p class="card-text" align="justify">En el siguiente módulo se puede agregar y manipular la información de todos los médicos</p>

                        @Html.ActionLink("Llévame al módulo", "Create", "Medicos", "", new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
      
            <div class="col-4">
                <div class="card border-info" style="width: 18rem;">
                    <img src="~/img/paciente.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                    <div class="card-body">
                        <h5 class="card-title"><b>Pacientes</b></h5>
                        <p class="card-text" align="justify">En el siguiente módulo se puede agregar y manipular la información de todos los pacientes</p>
                        @Html.ActionLink("Llévame al módulo", "Create", "Pacientes", "", new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
          
            <div class="col-4">
                <div class="card border-info" style="width: 18rem;">
                    <img src="~/img/habitacion.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                    <div class="card-body">
                        <h5 class="card-title"><b>Habitaciones</b></h5>
                        <p class="card-text" align="justify">En el siguiente módulo se puede agregar y manipular la información de todas las habitaciones</p>
                        @Html.ActionLink("Llévame al módulo", "Create", "Habitaciones", "", new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>

ProyectoFinal/ProyectoFinal/Views/Home/Procesos.cshtml
@{
    ViewBag.Title = "Procesos";
}
<br />
<h2>Procesos</h2>
<br />
<div class="container mt-5">
    <div class="row">
        <div class="col-4">
            <div class="card border-info" style="width: 18rem;">
                <img src="~/img/citas.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                <div class="card-body">
                    <h5 class="card-title"><b>Citas médicas</b></h5>
                    <p class="card-text" align="justify">En el siguiente módulo se le reserverá una cita a determinada fecha y hora con determinado doctor </p>

                    @Html.ActionLink("Llévame al módulo", "Create", "Citas", "", new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
        <br />
        <div class="col-4">
            <div class="card border-info" style="width: 18rem;">
                <img src="~/img/ingreso.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                <div class="card-body">
                    <h5 class="card-title"><b>Ingresos</b></h5>
                    <p class="card-text" align="justify">En el siguiente módulo se ingresará en una habitación a determinado paciente                    
                    </p>
                    <br/>
                    @Html.ActionLink("Llévame al módulo", "Create", "Ingresos", "", new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
        <br />
        <div class="col-4">
            <div class="card border-info" style="width: 18rem;">
                <img src="~/img/alta.jpg" class="card-img-top imagen-carta" alt="..." width="200px" height="200px">
                <div class="card-body">
                    <h5 class="card-title"><b>Alta médica</b></h5>
                    <p class="card-text" align="justify">En el siguiente módulo se recupera el registro de ingreso para dar el alta del paciente</p>
                    @Html.ActionLink("Llévame al módulo", "Create", "Altas", "", new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
    </div>

</div>